version: '3.5'

services:
  postgres:
    container_name: postgres_api_livros
    image: postgres
    environment:
      POSTGRES_USER: admin_livros
      POSTGRES_PASSWORD: '@CT1_Guerreiro'
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin_livros
      PGADMIN_DEFAULT_PASSWORD: '@CT1_Guerreiro'
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
